import { Mat } from '../../core/src/Mat';

type COLORMAP_AUTUMN = 0;
type COLORMAP_BONE = 1;
type COLORMAP_JET = 2;
type COLORMAP_WINTER = 3;
type COLORMAP_RAINBOW = 4;
type COLORMAP_OCEAN = 5;
type COLORMAP_SUMMER = 6;
type COLORMAP_SPRING = 7;
type COLORMAP_COOL = 8;
type COLORMAP_HSV = 9;
type COLORMAP_PINK = 10;
type COLORMAP_HOT = 11;
type COLORMAP_PARULA = 12;
type COLORMAP_MAGMA = 13;
type COLORMAP_INFERNO = 14;
type COLORMAP_PLASMA = 15;
type COLORMAP_VIRIDIS = 16;
type COLORMAP_CIVIDIS = 17;
type COLORMAP_TWILIGHT = 18;
type COLORMAP_TWILIGHT_SHIFTED = 19;
type COLORMAP_TURBO = 20;
type COLORMAP_DEEPGREEN = 21;

export type ColormapTypes =
    | COLORMAP_AUTUMN
    | COLORMAP_BONE
    | COLORMAP_JET
    | COLORMAP_WINTER
    | COLORMAP_RAINBOW
    | COLORMAP_OCEAN
    | COLORMAP_SUMMER
    | COLORMAP_SPRING
    | COLORMAP_COOL
    | COLORMAP_HSV
    | COLORMAP_PINK
    | COLORMAP_HOT
    | COLORMAP_PARULA
    | COLORMAP_MAGMA
    | COLORMAP_INFERNO
    | COLORMAP_PLASMA
    | COLORMAP_VIRIDIS
    | COLORMAP_CIVIDIS
    | COLORMAP_TWILIGHT
    | COLORMAP_TWILIGHT_SHIFTED
    | COLORMAP_TURBO
    | COLORMAP_DEEPGREEN;

export interface IColormapTypes {
    COLORMAP_AUTUMN: COLORMAP_AUTUMN;
    COLORMAP_BONE: COLORMAP_BONE;
    COLORMAP_JET: COLORMAP_JET;
    COLORMAP_WINTER: COLORMAP_WINTER;
    COLORMAP_RAINBOW: COLORMAP_RAINBOW;
    COLORMAP_OCEAN: COLORMAP_OCEAN;
    COLORMAP_SUMMER: COLORMAP_SUMMER;
    COLORMAP_SPRING: COLORMAP_SPRING;
    COLORMAP_COOL: COLORMAP_COOL;
    COLORMAP_HSV: COLORMAP_HSV;
    COLORMAP_PINK: COLORMAP_PINK;
    COLORMAP_HOT: COLORMAP_HOT;
    COLORMAP_PARULA: COLORMAP_PARULA;
    COLORMAP_MAGMA: COLORMAP_MAGMA;
    COLORMAP_INFERNO: COLORMAP_INFERNO;
    COLORMAP_PLASMA: COLORMAP_PLASMA;
    COLORMAP_VIRIDIS: COLORMAP_VIRIDIS;
    COLORMAP_CIVIDIS: COLORMAP_CIVIDIS;
    COLORMAP_TWILIGHT: COLORMAP_TWILIGHT;
    COLORMAP_TWILIGHT_SHIFTED: COLORMAP_TWILIGHT_SHIFTED;
    COLORMAP_TURBO: COLORMAP_TURBO;
    COLORMAP_DEEPGREEN: COLORMAP_DEEPGREEN;
}

export interface ColorMap {
    applyColorMap(src: Mat, dst: Mat, colormap: ColormapTypes): void;
}
