import { Mat } from './Mat';

type COLOR_BGR2BGRA = 0;
type COLOR_RGB2RGBA = COLOR_BGR2BGRA;
type COLOR_BGRA2BGR = 1;
type COLOR_RGBA2RGB = COLOR_BGRA2BGR;
type COLOR_BGR2RGBA = 2;
type COLOR_RGB2BGRA = COLOR_BGR2RGBA;
type COLOR_RGBA2BGR = 3;
type COLOR_BGRA2RGB = COLOR_RGBA2BGR;
type COLOR_BGR2RGB = 4;
type COLOR_RGB2BGR = COLOR_BGR2RGB;
type COLOR_BGRA2RGBA = 5;
type COLOR_RGBA2BGRA = COLOR_BGRA2RGBA;
type COLOR_BGR2GRAY = 6;
type COLOR_RGB2GRAY = 7;
type COLOR_GRAY2BGR = 8;
type COLOR_GRAY2RGB = COLOR_GRAY2BGR;
type COLOR_GRAY2BGRA = 9;
type COLOR_GRAY2RGBA = COLOR_GRAY2BGRA;
type COLOR_BGRA2GRAY = 10;
type COLOR_RGBA2GRAY = 11;
type COLOR_BGR2BGR565 = 12;
type COLOR_RGB2BGR565 = 13;
type COLOR_BGR5652BGR = 14;
type COLOR_BGR5652RGB = 15;
type COLOR_BGRA2BGR565 = 16;
type COLOR_RGBA2BGR565 = 17;
type COLOR_BGR5652BGRA = 18;
type COLOR_BGR5652RGBA = 19;
type COLOR_GRAY2BGR565 = 20;
type COLOR_BGR5652GRAY = 21;
type COLOR_BGR2BGR555 = 22;
type COLOR_RGB2BGR555 = 23;
type COLOR_BGR5552BGR = 24;
type COLOR_BGR5552RGB = 25;
type COLOR_BGRA2BGR555 = 26;
type COLOR_RGBA2BGR555 = 27;
type COLOR_BGR5552BGRA = 28;
type COLOR_BGR5552RGBA = 29;
type COLOR_GRAY2BGR555 = 30;
type COLOR_BGR5552GRAY = 31;
type COLOR_BGR2XYZ = 32;
type COLOR_RGB2XYZ = 33;
type COLOR_XYZ2BGR = 34;
type COLOR_XYZ2RGB = 35;
type COLOR_BGR2YCrCb = 36;
type COLOR_RGB2YCrCb = 37;
type COLOR_YCrCb2BGR = 38;
type COLOR_YCrCb2RGB = 39;
type COLOR_BGR2HSV = 40;
type COLOR_RGB2HSV = 41;
type COLOR_BGR2Lab = 44;
type COLOR_RGB2Lab = 45;
type COLOR_BGR2Luv = 50;
type COLOR_RGB2Luv = 51;
type COLOR_BGR2HLS = 52;
type COLOR_RGB2HLS = 53;
type COLOR_HSV2BGR = 54;
type COLOR_HSV2RGB = 55;
type COLOR_Lab2BGR = 56;
type COLOR_Lab2RGB = 57;
type COLOR_Luv2BGR = 58;
type COLOR_Luv2RGB = 59;
type COLOR_HLS2BGR = 60;
type COLOR_HLS2RGB = 61;
type COLOR_BGR2HSV_FULL = 66;
type COLOR_RGB2HSV_FULL = 67;
type COLOR_BGR2HLS_FULL = 68;
type COLOR_RGB2HLS_FULL = 69;
type COLOR_HSV2BGR_FULL = 70;
type COLOR_HSV2RGB_FULL = 71;
type COLOR_HLS2BGR_FULL = 72;
type COLOR_HLS2RGB_FULL = 73;
type COLOR_LBGR2Lab = 74;
type COLOR_LRGB2Lab = 75;
type COLOR_LBGR2Luv = 76;
type COLOR_LRGB2Luv = 77;
type COLOR_Lab2LBGR = 78;
type COLOR_Lab2LRGB = 79;
type COLOR_Luv2LBGR = 80;
type COLOR_Luv2LRGB = 81;
type COLOR_BGR2YUV = 82;
type COLOR_RGB2YUV = 83;
type COLOR_YUV2BGR = 84;
type COLOR_YUV2RGB = 85;
type COLOR_YUV2RGB_NV12 = 90;
type COLOR_YUV2BGR_NV12 = 91;
type COLOR_YUV2RGB_NV21 = 92;
type COLOR_YUV2BGR_NV21 = 93;
type COLOR_YUV420sp2RGB = COLOR_YUV2RGB_NV21;
type COLOR_YUV420sp2BGR = COLOR_YUV2BGR_NV21;
type COLOR_YUV2RGBA_NV12 = 94;
type COLOR_YUV2BGRA_NV12 = 95;
type COLOR_YUV2RGBA_NV21 = 96;
type COLOR_YUV2BGRA_NV21 = 97;
type COLOR_YUV420sp2RGBA = COLOR_YUV2RGBA_NV21;
type COLOR_YUV420sp2BGRA = COLOR_YUV2BGRA_NV21;
type COLOR_YUV2RGB_YV12 = 98;
type COLOR_YUV2BGR_YV12 = 99;
type COLOR_YUV2RGB_IYUV = 100;
type COLOR_YUV2BGR_IYUV = 101;
type COLOR_YUV2RGB_I420 = COLOR_YUV2RGB_IYUV;
type COLOR_YUV2BGR_I420 = COLOR_YUV2BGR_IYUV;
type COLOR_YUV420p2RGB = COLOR_YUV2RGB_YV12;
type COLOR_YUV420p2BGR = COLOR_YUV2BGR_YV12;
type COLOR_YUV2RGBA_YV12 = 102;
type COLOR_YUV2BGRA_YV12 = 103;
type COLOR_YUV2RGBA_IYUV = 104;
type COLOR_YUV2BGRA_IYUV = 105;
type COLOR_YUV2RGBA_I420 = COLOR_YUV2RGBA_IYUV;
type COLOR_YUV2BGRA_I420 = COLOR_YUV2BGRA_IYUV;
type COLOR_YUV420p2RGBA = COLOR_YUV2RGBA_YV12;
type COLOR_YUV420p2BGRA = COLOR_YUV2BGRA_YV12;
type COLOR_YUV2GRAY_420 = 106;
type COLOR_YUV2GRAY_NV21 = COLOR_YUV2GRAY_420;
type COLOR_YUV2GRAY_NV12 = COLOR_YUV2GRAY_420;
type COLOR_YUV2GRAY_YV12 = COLOR_YUV2GRAY_420;
type COLOR_YUV2GRAY_IYUV = COLOR_YUV2GRAY_420;
type COLOR_YUV2GRAY_I420 = COLOR_YUV2GRAY_420;
type COLOR_YUV420sp2GRAY = COLOR_YUV2GRAY_420;
type COLOR_YUV420p2GRAY = COLOR_YUV2GRAY_420;
type COLOR_YUV2RGB_UYVY = 107;
type COLOR_YUV2BGR_UYVY = 108;
type COLOR_YUV2RGB_Y422 = COLOR_YUV2RGB_UYVY;
type COLOR_YUV2BGR_Y422 = COLOR_YUV2BGR_UYVY;
type COLOR_YUV2RGB_UYNV = COLOR_YUV2RGB_UYVY;
type COLOR_YUV2BGR_UYNV = COLOR_YUV2BGR_UYVY;
type COLOR_YUV2RGBA_UYVY = 111;
type COLOR_YUV2BGRA_UYVY = 112;
type COLOR_YUV2RGBA_Y422 = COLOR_YUV2RGBA_UYVY;
type COLOR_YUV2BGRA_Y422 = COLOR_YUV2BGRA_UYVY;
type COLOR_YUV2RGBA_UYNV = COLOR_YUV2RGBA_UYVY;
type COLOR_YUV2BGRA_UYNV = COLOR_YUV2BGRA_UYVY;
type COLOR_YUV2RGB_YUY2 = 115;
type COLOR_YUV2BGR_YUY2 = 116;
type COLOR_YUV2RGB_YVYU = 117;
type COLOR_YUV2BGR_YVYU = 118;
type COLOR_YUV2RGB_YUYV = COLOR_YUV2RGB_YUY2;
type COLOR_YUV2BGR_YUYV = COLOR_YUV2BGR_YUY2;
type COLOR_YUV2RGB_YUNV = COLOR_YUV2RGB_YUY2;
type COLOR_YUV2BGR_YUNV = COLOR_YUV2BGR_YUY2;
type COLOR_YUV2RGBA_YUY2 = 119;
type COLOR_YUV2BGRA_YUY2 = 120;
type COLOR_YUV2RGBA_YVYU = 121;
type COLOR_YUV2BGRA_YVYU = 122;
type COLOR_YUV2RGBA_YUYV = COLOR_YUV2RGBA_YUY2;
type COLOR_YUV2BGRA_YUYV = COLOR_YUV2BGRA_YUY2;
type COLOR_YUV2RGBA_YUNV = COLOR_YUV2RGBA_YUY2;
type COLOR_YUV2BGRA_YUNV = COLOR_YUV2BGRA_YUY2;
type COLOR_YUV2GRAY_UYVY = 123;
type COLOR_YUV2GRAY_YUY2 = 124;
type COLOR_YUV2GRAY_Y422 = COLOR_YUV2GRAY_UYVY;
type COLOR_YUV2GRAY_UYNV = COLOR_YUV2GRAY_UYVY;
type COLOR_YUV2GRAY_YVYU = COLOR_YUV2GRAY_YUY2;
type COLOR_YUV2GRAY_YUYV = COLOR_YUV2GRAY_YUY2;
type COLOR_YUV2GRAY_YUNV = COLOR_YUV2GRAY_YUY2;
type COLOR_RGBA2mRGBA = 125;
type COLOR_mRGBA2RGBA = 126;
type COLOR_RGB2YUV_I420 = 127;
type COLOR_BGR2YUV_I420 = 128;
type COLOR_RGB2YUV_IYUV = COLOR_RGB2YUV_I420;
type COLOR_BGR2YUV_IYUV = COLOR_BGR2YUV_I420;
type COLOR_RGBA2YUV_I420 = 129;
type COLOR_BGRA2YUV_I420 = 130;
type COLOR_RGBA2YUV_IYUV = COLOR_RGBA2YUV_I420;
type COLOR_BGRA2YUV_IYUV = COLOR_BGRA2YUV_I420;
type COLOR_RGB2YUV_YV12 = 131;
type COLOR_BGR2YUV_YV12 = 132;
type COLOR_RGBA2YUV_YV12 = 133;
type COLOR_BGRA2YUV_YV12 = 134;
type COLOR_BayerBG2BGR = 46;
type COLOR_BayerGB2BGR = 47;
type COLOR_BayerRG2BGR = 48;
type COLOR_BayerGR2BGR = 49;
type COLOR_BayerBG2RGB = COLOR_BayerRG2BGR;
type COLOR_BayerGB2RGB = COLOR_BayerGR2BGR;
type COLOR_BayerRG2RGB = COLOR_BayerBG2BGR;
type COLOR_BayerGR2RGB = COLOR_BayerGB2BGR;
type COLOR_BayerBG2GRAY = 86;
type COLOR_BayerGB2GRAY = 87;
type COLOR_BayerRG2GRAY = 88;
type COLOR_BayerGR2GRAY = 89;
type COLOR_BayerBG2BGR_VNG = 62;
type COLOR_BayerGB2BGR_VNG = 63;
type COLOR_BayerRG2BGR_VNG = 64;
type COLOR_BayerGR2BGR_VNG = 65;
type COLOR_BayerBG2RGB_VNG = COLOR_BayerRG2BGR_VNG;
type COLOR_BayerGB2RGB_VNG = COLOR_BayerGR2BGR_VNG;
type COLOR_BayerRG2RGB_VNG = COLOR_BayerBG2BGR_VNG;
type COLOR_BayerGR2RGB_VNG = COLOR_BayerGB2BGR_VNG;
type COLOR_BayerBG2BGR_EA = 135;
type COLOR_BayerGB2BGR_EA = 136;
type COLOR_BayerRG2BGR_EA = 137;
type COLOR_BayerGR2BGR_EA = 138;
type COLOR_BayerBG2RGB_EA = COLOR_BayerRG2BGR_EA;
type COLOR_BayerGB2RGB_EA = COLOR_BayerGR2BGR_EA;
type COLOR_BayerRG2RGB_EA = COLOR_BayerBG2BGR_EA;
type COLOR_BayerGR2RGB_EA = COLOR_BayerGB2BGR_EA;
type COLOR_BayerBG2BGRA = 139;
type COLOR_BayerGB2BGRA = 140;
type COLOR_BayerRG2BGRA = 141;
type COLOR_BayerGR2BGRA = 142;
type COLOR_BayerBG2RGBA = COLOR_BayerRG2BGRA;
type COLOR_BayerGB2RGBA = COLOR_BayerGR2BGRA;
type COLOR_BayerRG2RGBA = COLOR_BayerBG2BGRA;
type COLOR_BayerGR2RGBA = COLOR_BayerGB2BGRA;
type COLOR_COLORCVT_MAX = 143;

export interface IColorConversionCodes {
    COLOR_BGR2BGRA: COLOR_BGR2BGRA;
    COLOR_RGB2RGBA: COLOR_RGB2RGBA;
    COLOR_BGRA2BGR: COLOR_BGRA2BGR;
    COLOR_RGBA2RGB: COLOR_RGBA2RGB;
    COLOR_BGR2RGBA: COLOR_BGR2RGBA;
    COLOR_RGB2BGRA: COLOR_RGB2BGRA;
    COLOR_RGBA2BGR: COLOR_RGBA2BGR;
    COLOR_BGRA2RGB: COLOR_BGRA2RGB;
    COLOR_BGR2RGB: COLOR_BGR2RGB;
    COLOR_RGB2BGR: COLOR_RGB2BGR;
    COLOR_BGRA2RGBA: COLOR_BGRA2RGBA;
    COLOR_RGBA2BGRA: COLOR_RGBA2BGRA;
    COLOR_BGR2GRAY: COLOR_BGR2GRAY;
    COLOR_RGB2GRAY: COLOR_RGB2GRAY;
    COLOR_GRAY2BGR: COLOR_GRAY2BGR;
    COLOR_GRAY2RGB: COLOR_GRAY2RGB;
    COLOR_GRAY2BGRA: COLOR_GRAY2BGRA;
    COLOR_GRAY2RGBA: COLOR_GRAY2RGBA;
    COLOR_BGRA2GRAY: COLOR_BGRA2GRAY;
    COLOR_RGBA2GRAY: COLOR_RGBA2GRAY;
    COLOR_BGR2BGR565: COLOR_BGR2BGR565;
    COLOR_RGB2BGR565: COLOR_RGB2BGR565;
    COLOR_BGR5652BGR: COLOR_BGR5652BGR;
    COLOR_BGR5652RGB: COLOR_BGR5652RGB;
    COLOR_BGRA2BGR565: COLOR_BGRA2BGR565;
    COLOR_RGBA2BGR565: COLOR_RGBA2BGR565;
    COLOR_BGR5652BGRA: COLOR_BGR5652BGRA;
    COLOR_BGR5652RGBA: COLOR_BGR5652RGBA;
    COLOR_GRAY2BGR565: COLOR_GRAY2BGR565;
    COLOR_BGR5652GRAY: COLOR_BGR5652GRAY;
    COLOR_BGR2BGR555: COLOR_BGR2BGR555;
    COLOR_RGB2BGR555: COLOR_RGB2BGR555;
    COLOR_BGR5552BGR: COLOR_BGR5552BGR;
    COLOR_BGR5552RGB: COLOR_BGR5552RGB;
    COLOR_BGRA2BGR555: COLOR_BGRA2BGR555;
    COLOR_RGBA2BGR555: COLOR_RGBA2BGR555;
    COLOR_BGR5552BGRA: COLOR_BGR5552BGRA;
    COLOR_BGR5552RGBA: COLOR_BGR5552RGBA;
    COLOR_GRAY2BGR555: COLOR_GRAY2BGR555;
    COLOR_BGR5552GRAY: COLOR_BGR5552GRAY;
    COLOR_BGR2XYZ: COLOR_BGR2XYZ;
    COLOR_RGB2XYZ: COLOR_RGB2XYZ;
    COLOR_XYZ2BGR: COLOR_XYZ2BGR;
    COLOR_XYZ2RGB: COLOR_XYZ2RGB;
    COLOR_BGR2YCrCb: COLOR_BGR2YCrCb;
    COLOR_RGB2YCrCb: COLOR_RGB2YCrCb;
    COLOR_YCrCb2BGR: COLOR_YCrCb2BGR;
    COLOR_YCrCb2RGB: COLOR_YCrCb2RGB;
    COLOR_BGR2HSV: COLOR_BGR2HSV;
    COLOR_RGB2HSV: COLOR_RGB2HSV;
    COLOR_BGR2Lab: COLOR_BGR2Lab;
    COLOR_RGB2Lab: COLOR_RGB2Lab;
    COLOR_BGR2Luv: COLOR_BGR2Luv;
    COLOR_RGB2Luv: COLOR_RGB2Luv;
    COLOR_BGR2HLS: COLOR_BGR2HLS;
    COLOR_RGB2HLS: COLOR_RGB2HLS;
    COLOR_HSV2BGR: COLOR_HSV2BGR;
    COLOR_HSV2RGB: COLOR_HSV2RGB;
    COLOR_Lab2BGR: COLOR_Lab2BGR;
    COLOR_Lab2RGB: COLOR_Lab2RGB;
    COLOR_Luv2BGR: COLOR_Luv2BGR;
    COLOR_Luv2RGB: COLOR_Luv2RGB;
    COLOR_HLS2BGR: COLOR_HLS2BGR;
    COLOR_HLS2RGB: COLOR_HLS2RGB;
    COLOR_BGR2HSV_FULL: COLOR_BGR2HSV_FULL;
    COLOR_RGB2HSV_FULL: COLOR_RGB2HSV_FULL;
    COLOR_BGR2HLS_FULL: COLOR_BGR2HLS_FULL;
    COLOR_RGB2HLS_FULL: COLOR_RGB2HLS_FULL;
    COLOR_HSV2BGR_FULL: COLOR_HSV2BGR_FULL;
    COLOR_HSV2RGB_FULL: COLOR_HSV2RGB_FULL;
    COLOR_HLS2BGR_FULL: COLOR_HLS2BGR_FULL;
    COLOR_HLS2RGB_FULL: COLOR_HLS2RGB_FULL;
    COLOR_LBGR2Lab: COLOR_LBGR2Lab;
    COLOR_LRGB2Lab: COLOR_LRGB2Lab;
    COLOR_LBGR2Luv: COLOR_LBGR2Luv;
    COLOR_LRGB2Luv: COLOR_LRGB2Luv;
    COLOR_Lab2LBGR: COLOR_Lab2LBGR;
    COLOR_Lab2LRGB: COLOR_Lab2LRGB;
    COLOR_Luv2LBGR: COLOR_Luv2LBGR;
    COLOR_Luv2LRGB: COLOR_Luv2LRGB;
    COLOR_BGR2YUV: COLOR_BGR2YUV;
    COLOR_RGB2YUV: COLOR_RGB2YUV;
    COLOR_YUV2BGR: COLOR_YUV2BGR;
    COLOR_YUV2RGB: COLOR_YUV2RGB;
    COLOR_YUV2RGB_NV12: COLOR_YUV2RGB_NV12;
    COLOR_YUV2BGR_NV12: COLOR_YUV2BGR_NV12;
    COLOR_YUV2RGB_NV21: COLOR_YUV2RGB_NV21;
    COLOR_YUV2BGR_NV21: COLOR_YUV2BGR_NV21;
    COLOR_YUV420sp2RGB: COLOR_YUV420sp2RGB;
    COLOR_YUV420sp2BGR: COLOR_YUV420sp2BGR;
    COLOR_YUV2RGBA_NV12: COLOR_YUV2RGBA_NV12;
    COLOR_YUV2BGRA_NV12: COLOR_YUV2BGRA_NV12;
    COLOR_YUV2RGBA_NV21: COLOR_YUV2RGBA_NV21;
    COLOR_YUV2BGRA_NV21: COLOR_YUV2BGRA_NV21;
    COLOR_YUV420sp2RGBA: COLOR_YUV420sp2RGBA;
    COLOR_YUV420sp2BGRA: COLOR_YUV420sp2BGRA;
    COLOR_YUV2RGB_YV12: COLOR_YUV2RGB_YV12;
    COLOR_YUV2BGR_YV12: COLOR_YUV2BGR_YV12;
    COLOR_YUV2RGB_IYUV: COLOR_YUV2RGB_IYUV;
    COLOR_YUV2BGR_IYUV: COLOR_YUV2BGR_IYUV;
    COLOR_YUV2RGB_I420: COLOR_YUV2RGB_I420;
    COLOR_YUV2BGR_I420: COLOR_YUV2BGR_I420;
    COLOR_YUV420p2RGB: COLOR_YUV420p2RGB;
    COLOR_YUV420p2BGR: COLOR_YUV420p2BGR;
    COLOR_YUV2RGBA_YV12: COLOR_YUV2RGBA_YV12;
    COLOR_YUV2BGRA_YV12: COLOR_YUV2BGRA_YV12;
    COLOR_YUV2RGBA_IYUV: COLOR_YUV2RGBA_IYUV;
    COLOR_YUV2BGRA_IYUV: COLOR_YUV2BGRA_IYUV;
    COLOR_YUV2RGBA_I420: COLOR_YUV2RGBA_I420;
    COLOR_YUV2BGRA_I420: COLOR_YUV2BGRA_I420;
    COLOR_YUV420p2RGBA: COLOR_YUV420p2RGBA;
    COLOR_YUV420p2BGRA: COLOR_YUV420p2BGRA;
    COLOR_YUV2GRAY_420: COLOR_YUV2GRAY_420;
    COLOR_YUV2GRAY_NV21: COLOR_YUV2GRAY_NV21;
    COLOR_YUV2GRAY_NV12: COLOR_YUV2GRAY_NV12;
    COLOR_YUV2GRAY_YV12: COLOR_YUV2GRAY_YV12;
    COLOR_YUV2GRAY_IYUV: COLOR_YUV2GRAY_IYUV;
    COLOR_YUV2GRAY_I420: COLOR_YUV2GRAY_I420;
    COLOR_YUV420sp2GRAY: COLOR_YUV420sp2GRAY;
    COLOR_YUV420p2GRAY: COLOR_YUV420p2GRAY;
    COLOR_YUV2RGB_UYVY: COLOR_YUV2RGB_UYVY;
    COLOR_YUV2BGR_UYVY: COLOR_YUV2BGR_UYVY;
    COLOR_YUV2RGB_Y422: COLOR_YUV2RGB_Y422;
    COLOR_YUV2BGR_Y422: COLOR_YUV2BGR_Y422;
    COLOR_YUV2RGB_UYNV: COLOR_YUV2RGB_UYNV;
    COLOR_YUV2BGR_UYNV: COLOR_YUV2BGR_UYNV;
    COLOR_YUV2RGBA_UYVY: COLOR_YUV2RGBA_UYVY;
    COLOR_YUV2BGRA_UYVY: COLOR_YUV2BGRA_UYVY;
    COLOR_YUV2RGBA_Y422: COLOR_YUV2RGBA_Y422;
    COLOR_YUV2BGRA_Y422: COLOR_YUV2BGRA_Y422;
    COLOR_YUV2RGBA_UYNV: COLOR_YUV2RGBA_UYNV;
    COLOR_YUV2BGRA_UYNV: COLOR_YUV2BGRA_UYNV;
    COLOR_YUV2RGB_YUY2: COLOR_YUV2RGB_YUY2;
    COLOR_YUV2BGR_YUY2: COLOR_YUV2BGR_YUY2;
    COLOR_YUV2RGB_YVYU: COLOR_YUV2RGB_YVYU;
    COLOR_YUV2BGR_YVYU: COLOR_YUV2BGR_YVYU;
    COLOR_YUV2RGB_YUYV: COLOR_YUV2RGB_YUYV;
    COLOR_YUV2BGR_YUYV: COLOR_YUV2BGR_YUYV;
    COLOR_YUV2RGB_YUNV: COLOR_YUV2RGB_YUNV;
    COLOR_YUV2BGR_YUNV: COLOR_YUV2BGR_YUNV;
    COLOR_YUV2RGBA_YUY2: COLOR_YUV2RGBA_YUY2;
    COLOR_YUV2BGRA_YUY2: COLOR_YUV2BGRA_YUY2;
    COLOR_YUV2RGBA_YVYU: COLOR_YUV2RGBA_YVYU;
    COLOR_YUV2BGRA_YVYU: COLOR_YUV2BGRA_YVYU;
    COLOR_YUV2RGBA_YUYV: COLOR_YUV2RGBA_YUYV;
    COLOR_YUV2BGRA_YUYV: COLOR_YUV2BGRA_YUYV;
    COLOR_YUV2RGBA_YUNV: COLOR_YUV2RGBA_YUNV;
    COLOR_YUV2BGRA_YUNV: COLOR_YUV2BGRA_YUNV;
    COLOR_YUV2GRAY_UYVY: COLOR_YUV2GRAY_UYVY;
    COLOR_YUV2GRAY_YUY2: COLOR_YUV2GRAY_YUY2;
    COLOR_YUV2GRAY_Y422: COLOR_YUV2GRAY_Y422;
    COLOR_YUV2GRAY_UYNV: COLOR_YUV2GRAY_UYNV;
    COLOR_YUV2GRAY_YVYU: COLOR_YUV2GRAY_YVYU;
    COLOR_YUV2GRAY_YUYV: COLOR_YUV2GRAY_YUYV;
    COLOR_YUV2GRAY_YUNV: COLOR_YUV2GRAY_YUNV;
    COLOR_RGBA2mRGBA: COLOR_RGBA2mRGBA;
    COLOR_mRGBA2RGBA: COLOR_mRGBA2RGBA;
    COLOR_RGB2YUV_I420: COLOR_RGB2YUV_I420;
    COLOR_BGR2YUV_I420: COLOR_BGR2YUV_I420;
    COLOR_RGB2YUV_IYUV: COLOR_RGB2YUV_IYUV;
    COLOR_BGR2YUV_IYUV: COLOR_BGR2YUV_IYUV;
    COLOR_RGBA2YUV_I420: COLOR_RGBA2YUV_I420;
    COLOR_BGRA2YUV_I420: COLOR_BGRA2YUV_I420;
    COLOR_RGBA2YUV_IYUV: COLOR_RGBA2YUV_IYUV;
    COLOR_BGRA2YUV_IYUV: COLOR_BGRA2YUV_IYUV;
    COLOR_RGB2YUV_YV12: COLOR_RGB2YUV_YV12;
    COLOR_BGR2YUV_YV12: COLOR_BGR2YUV_YV12;
    COLOR_RGBA2YUV_YV12: COLOR_RGBA2YUV_YV12;
    COLOR_BGRA2YUV_YV12: COLOR_BGRA2YUV_YV12;
    COLOR_BayerBG2BGR: COLOR_BayerBG2BGR;
    COLOR_BayerGB2BGR: COLOR_BayerGB2BGR;
    COLOR_BayerRG2BGR: COLOR_BayerRG2BGR;
    COLOR_BayerGR2BGR: COLOR_BayerGR2BGR;
    COLOR_BayerBG2RGB: COLOR_BayerBG2RGB;
    COLOR_BayerGB2RGB: COLOR_BayerGB2RGB;
    COLOR_BayerRG2RGB: COLOR_BayerRG2RGB;
    COLOR_BayerGR2RGB: COLOR_BayerGR2RGB;
    COLOR_BayerBG2GRAY: COLOR_BayerBG2GRAY;
    COLOR_BayerGB2GRAY: COLOR_BayerGB2GRAY;
    COLOR_BayerRG2GRAY: COLOR_BayerRG2GRAY;
    COLOR_BayerGR2GRAY: COLOR_BayerGR2GRAY;
    COLOR_BayerBG2BGR_VNG: COLOR_BayerBG2BGR_VNG;
    COLOR_BayerGB2BGR_VNG: COLOR_BayerGB2BGR_VNG;
    COLOR_BayerRG2BGR_VNG: COLOR_BayerRG2BGR_VNG;
    COLOR_BayerGR2BGR_VNG: COLOR_BayerGR2BGR_VNG;
    COLOR_BayerBG2RGB_VNG: COLOR_BayerBG2RGB_VNG;
    COLOR_BayerGB2RGB_VNG: COLOR_BayerGB2RGB_VNG;
    COLOR_BayerRG2RGB_VNG: COLOR_BayerRG2RGB_VNG;
    COLOR_BayerGR2RGB_VNG: COLOR_BayerGR2RGB_VNG;
    COLOR_BayerBG2BGR_EA: COLOR_BayerBG2BGR_EA;
    COLOR_BayerGB2BGR_EA: COLOR_BayerGB2BGR_EA;
    COLOR_BayerRG2BGR_EA: COLOR_BayerRG2BGR_EA;
    COLOR_BayerGR2BGR_EA: COLOR_BayerGR2BGR_EA;
    COLOR_BayerBG2RGB_EA: COLOR_BayerBG2RGB_EA;
    COLOR_BayerGB2RGB_EA: COLOR_BayerGB2RGB_EA;
    COLOR_BayerRG2RGB_EA: COLOR_BayerRG2RGB_EA;
    COLOR_BayerGR2RGB_EA: COLOR_BayerGR2RGB_EA;
    COLOR_BayerBG2BGRA: COLOR_BayerBG2BGRA;
    COLOR_BayerGB2BGRA: COLOR_BayerGB2BGRA;
    COLOR_BayerRG2BGRA: COLOR_BayerRG2BGRA;
    COLOR_BayerGR2BGRA: COLOR_BayerGR2BGRA;
    COLOR_BayerBG2RGBA: COLOR_BayerBG2RGBA;
    COLOR_BayerGB2RGBA: COLOR_BayerGB2RGBA;
    COLOR_BayerRG2RGBA: COLOR_BayerRG2RGBA;
    COLOR_BayerGR2RGBA: COLOR_BayerGR2RGBA;
    COLORCOLORCVT_MAX: COLOR_COLORCVT_MAX;
}

export type ColorConversionCodes =
    | COLOR_BGR2BGRA
    | COLOR_RGB2RGBA
    | COLOR_BGRA2BGR
    | COLOR_RGBA2RGB
    | COLOR_BGR2RGBA
    | COLOR_RGB2BGRA
    | COLOR_RGBA2BGR
    | COLOR_BGRA2RGB
    | COLOR_BGR2RGB
    | COLOR_RGB2BGR
    | COLOR_BGRA2RGBA
    | COLOR_RGBA2BGRA
    | COLOR_BGR2GRAY
    | COLOR_RGB2GRAY
    | COLOR_GRAY2BGR
    | COLOR_GRAY2RGB
    | COLOR_GRAY2BGRA
    | COLOR_GRAY2RGBA
    | COLOR_BGRA2GRAY
    | COLOR_RGBA2GRAY
    | COLOR_BGR2BGR565
    | COLOR_RGB2BGR565
    | COLOR_BGR5652BGR
    | COLOR_BGR5652RGB
    | COLOR_BGRA2BGR565
    | COLOR_RGBA2BGR565
    | COLOR_BGR5652BGRA
    | COLOR_BGR5652RGBA
    | COLOR_GRAY2BGR565
    | COLOR_BGR5652GRAY
    | COLOR_BGR2BGR555
    | COLOR_RGB2BGR555
    | COLOR_BGR5552BGR
    | COLOR_BGR5552RGB
    | COLOR_BGRA2BGR555
    | COLOR_RGBA2BGR555
    | COLOR_BGR5552BGRA
    | COLOR_BGR5552RGBA
    | COLOR_GRAY2BGR555
    | COLOR_BGR5552GRAY
    | COLOR_BGR2XYZ
    | COLOR_RGB2XYZ
    | COLOR_XYZ2BGR
    | COLOR_XYZ2RGB
    | COLOR_BGR2YCrCb
    | COLOR_RGB2YCrCb
    | COLOR_YCrCb2BGR
    | COLOR_YCrCb2RGB
    | COLOR_BGR2HSV
    | COLOR_RGB2HSV
    | COLOR_BGR2Lab
    | COLOR_RGB2Lab
    | COLOR_BGR2Luv
    | COLOR_RGB2Luv
    | COLOR_BGR2HLS
    | COLOR_RGB2HLS
    | COLOR_HSV2BGR
    | COLOR_HSV2RGB
    | COLOR_Lab2BGR
    | COLOR_Lab2RGB
    | COLOR_Luv2BGR
    | COLOR_Luv2RGB
    | COLOR_HLS2BGR
    | COLOR_HLS2RGB
    | COLOR_BGR2HSV_FULL
    | COLOR_RGB2HSV_FULL
    | COLOR_BGR2HLS_FULL
    | COLOR_RGB2HLS_FULL
    | COLOR_HSV2BGR_FULL
    | COLOR_HSV2RGB_FULL
    | COLOR_HLS2BGR_FULL
    | COLOR_HLS2RGB_FULL
    | COLOR_LBGR2Lab
    | COLOR_LRGB2Lab
    | COLOR_LBGR2Luv
    | COLOR_LRGB2Luv
    | COLOR_Lab2LBGR
    | COLOR_Lab2LRGB
    | COLOR_Luv2LBGR
    | COLOR_Luv2LRGB
    | COLOR_BGR2YUV
    | COLOR_RGB2YUV
    | COLOR_YUV2BGR
    | COLOR_YUV2RGB
    | COLOR_YUV2RGB_NV12
    | COLOR_YUV2BGR_NV12
    | COLOR_YUV2RGB_NV21
    | COLOR_YUV2BGR_NV21
    | COLOR_YUV420sp2RGB
    | COLOR_YUV420sp2BGR
    | COLOR_YUV2RGBA_NV12
    | COLOR_YUV2BGRA_NV12
    | COLOR_YUV2RGBA_NV21
    | COLOR_YUV2BGRA_NV21
    | COLOR_YUV420sp2RGBA
    | COLOR_YUV420sp2BGRA
    | COLOR_YUV2RGB_YV12
    | COLOR_YUV2BGR_YV12
    | COLOR_YUV2RGB_IYUV
    | COLOR_YUV2BGR_IYUV
    | COLOR_YUV2RGB_I420
    | COLOR_YUV2BGR_I420
    | COLOR_YUV420p2RGB
    | COLOR_YUV420p2BGR
    | COLOR_YUV2RGBA_YV12
    | COLOR_YUV2BGRA_YV12
    | COLOR_YUV2RGBA_IYUV
    | COLOR_YUV2BGRA_IYUV
    | COLOR_YUV2RGBA_I420
    | COLOR_YUV2BGRA_I420
    | COLOR_YUV420p2RGBA
    | COLOR_YUV420p2BGRA
    | COLOR_YUV2GRAY_420
    | COLOR_YUV2GRAY_NV21
    | COLOR_YUV2GRAY_NV12
    | COLOR_YUV2GRAY_YV12
    | COLOR_YUV2GRAY_IYUV
    | COLOR_YUV2GRAY_I420
    | COLOR_YUV420sp2GRAY
    | COLOR_YUV420p2GRAY
    | COLOR_YUV2RGB_UYVY
    | COLOR_YUV2BGR_UYVY
    | COLOR_YUV2RGB_Y422
    | COLOR_YUV2BGR_Y422
    | COLOR_YUV2RGB_UYNV
    | COLOR_YUV2BGR_UYNV
    | COLOR_YUV2RGBA_UYVY
    | COLOR_YUV2BGRA_UYVY
    | COLOR_YUV2RGBA_Y422
    | COLOR_YUV2BGRA_Y422
    | COLOR_YUV2RGBA_UYNV
    | COLOR_YUV2BGRA_UYNV
    | COLOR_YUV2RGB_YUY2
    | COLOR_YUV2BGR_YUY2
    | COLOR_YUV2RGB_YVYU
    | COLOR_YUV2BGR_YVYU
    | COLOR_YUV2RGB_YUYV
    | COLOR_YUV2BGR_YUYV
    | COLOR_YUV2RGB_YUNV
    | COLOR_YUV2BGR_YUNV
    | COLOR_YUV2RGBA_YUY2
    | COLOR_YUV2BGRA_YUY2
    | COLOR_YUV2RGBA_YVYU
    | COLOR_YUV2BGRA_YVYU
    | COLOR_YUV2RGBA_YUYV
    | COLOR_YUV2BGRA_YUYV
    | COLOR_YUV2RGBA_YUNV
    | COLOR_YUV2BGRA_YUNV
    | COLOR_YUV2GRAY_UYVY
    | COLOR_YUV2GRAY_YUY2
    | COLOR_YUV2GRAY_Y422
    | COLOR_YUV2GRAY_UYNV
    | COLOR_YUV2GRAY_YVYU
    | COLOR_YUV2GRAY_YUYV
    | COLOR_YUV2GRAY_YUNV
    | COLOR_RGBA2mRGBA
    | COLOR_mRGBA2RGBA
    | COLOR_RGB2YUV_I420
    | COLOR_BGR2YUV_I420
    | COLOR_RGB2YUV_IYUV
    | COLOR_BGR2YUV_IYUV
    | COLOR_RGBA2YUV_I420
    | COLOR_BGRA2YUV_I420
    | COLOR_RGBA2YUV_IYUV
    | COLOR_BGRA2YUV_IYUV
    | COLOR_RGB2YUV_YV12
    | COLOR_BGR2YUV_YV12
    | COLOR_RGBA2YUV_YV12
    | COLOR_BGRA2YUV_YV12
    | COLOR_BayerBG2BGR
    | COLOR_BayerGB2BGR
    | COLOR_BayerRG2BGR
    | COLOR_BayerGR2BGR
    | COLOR_BayerBG2RGB
    | COLOR_BayerGB2RGB
    | COLOR_BayerRG2RGB
    | COLOR_BayerGR2RGB
    | COLOR_BayerBG2GRAY
    | COLOR_BayerGB2GRAY
    | COLOR_BayerRG2GRAY
    | COLOR_BayerGR2GRAY
    | COLOR_BayerBG2BGR_VNG
    | COLOR_BayerGB2BGR_VNG
    | COLOR_BayerRG2BGR_VNG
    | COLOR_BayerGR2BGR_VNG
    | COLOR_BayerBG2RGB_VNG
    | COLOR_BayerGB2RGB_VNG
    | COLOR_BayerRG2RGB_VNG
    | COLOR_BayerGR2RGB_VNG
    | COLOR_BayerBG2BGR_EA
    | COLOR_BayerGB2BGR_EA
    | COLOR_BayerRG2BGR_EA
    | COLOR_BayerGR2BGR_EA
    | COLOR_BayerBG2RGB_EA
    | COLOR_BayerGB2RGB_EA
    | COLOR_BayerRG2RGB_EA
    | COLOR_BayerGR2RGB_EA
    | COLOR_BayerBG2BGRA
    | COLOR_BayerGB2BGRA
    | COLOR_BayerRG2BGRA
    | COLOR_BayerGR2BGRA
    | COLOR_BayerBG2RGBA
    | COLOR_BayerGB2RGBA
    | COLOR_BayerRG2RGBA
    | COLOR_BayerGR2RGBA
    | COLOR_COLORCVT_MAX;

export interface ColorConversions {
    /**
     * Converts an image from one color space to another.
     * @param src input image: 8-bit unsigned, 16-bit unsigned ( CV_16UC... ), or single-precision floating-point.
     * @param dst output image of the same size and depth as src.
     * @param code color space conversion code.
     * @param dstCn number of channels in the destination image; if the parameter is 0, the number of the channels is derived automatically from src and code.
     */
    cvtColor(src: Mat, dst: Mat, code: ColorConversionCodes, dstCn?: number): void;
    /**
     * Converts an image from one color space to another where the source image is stored in two planes. This function only supports YUV420 to RGB conversion as of now.
     * @param src1 8-bit image (CV_8U) of the Y plane.
     * @param src2 image containing interleaved U/V plane.
     * @param dst output image.
     * @param code Specifies the type of conversion
     */
    cvtColorTwoPlane(
        src1: Mat,
        src2: Mat,
        dst: Mat,
        code:
            | COLOR_YUV2BGR_NV12
            | COLOR_YUV2RGB_NV12
            | COLOR_YUV2BGRA_NV12
            | COLOR_YUV2RGBA_NV12
            | COLOR_YUV2BGR_NV21
            | COLOR_YUV2RGB_NV21
            | COLOR_YUV2BGRA_NV21
            | COLOR_YUV2RGBA_NV21
    ): void;
    /**
     * main function for all demosaicing processes
     * @param src input image: 8-bit unsigned or 16-bit unsigned.
     * @param dst output image of the same size and depth as src.
     * @param code Color space conversion code (see the description below).
     * @param dstCn number of channels in the destination image
     */
    demosaicing(
        src: Mat,
        dst: Mat,
        code: //Demosaicing using bilinear interpolation
        | COLOR_BayerBG2BGR
            | COLOR_BayerGB2BGR
            | COLOR_BayerRG2BGR
            | COLOR_BayerGR2BGR
            | COLOR_BayerBG2GRAY
            | COLOR_BayerGB2GRAY
            | COLOR_BayerRG2GRAY
            | COLOR_BayerGR2GRAY
            // Demosaicing using Variable Number of Gradients.
            | COLOR_BayerBG2BGR_VNG
            | COLOR_BayerGB2BGR_VNG
            | COLOR_BayerRG2BGR_VNG
            | COLOR_BayerGR2BGR_VNG
            // Edge-Aware Demosaicing.
            | COLOR_BayerBG2BGR_EA
            | COLOR_BayerGB2BGR_EA
            | COLOR_BayerRG2BGR_EA
            | COLOR_BayerGR2BGR_EA
            // Demosaicing with alpha channel
            | COLOR_BayerBG2BGRA
            | COLOR_BayerGB2BGRA
            | COLOR_BayerRG2BGRA
            | COLOR_BayerGR2BGRA,
        dstCn?: number
    ): void;
}
