type SORT_EVERY_ROW = 0;
type SORT_EVERY_COLUMN = 1;
type SORT_ASCENDING = 0;
type SORT_DESCENDING = 16;

export type SortFlags = SORT_EVERY_ROW | SORT_EVERY_COLUMN | SORT_ASCENDING | SORT_DESCENDING;

export interface ISortFlags {
    SORT_EVERY_ROW: SORT_EVERY_ROW;
    SORT_EVERY_COLUMN: SORT_EVERY_COLUMN;
    SORT_ASCENDING: SORT_ASCENDING;
    SORT_DESCENDING: SORT_DESCENDING;
}
